### PR TITLE
replace sigint signal handler, with atexit, to let run in a thread

### PR DESCRIPTION
**Pull request by shimondoodkin**

### CODE REVIEW

**Comment by shimondoodkin** [comment]
if there is merge conflict: final result example:
https://github.com/shimondoodkin/zero/blob/main/zero/server.py#L106-L111

**Comment by Ananto30** [comment]
Hi @shimondoodkin thanks for the PR!

Can you please add tests for using threads? TIA

**Comment by shimondoodkin** [comment]
> Hi @shimondoodkin thanks for the PR!
> 
> Can you please add tests for using threads? TIA

maybe yes. i will look into it (if all ok this week).

**Comment by Ananto30** [comment]
Hi @shimondoodkin just a gentle knock, if you have some time on this. I appreciate the work! :pray:

**Comment by Ananto30** [comment]
Hi @shimondoodkin thanks for the tests. I found some issues for server termination in the tests. I see you are trying to fix them, thanks for that! 🙌 But if you want you can ignore that. Just test for the threads should be enough. I am trying to fix them in this PR => https://github.com/Ananto30/zero/pull/28

**Comment by Ananto30** [comment]
Hi @shimondoodkin I have fixed the server close issue in this PR => https://github.com/Ananto30/zero/pull/28 (exactly these lines [server.py#111](https://github.com/Ananto30/zero/pull/28/files#diff-2f50c53b4b8570b5bb3652e6f0cf315fbd8df68f565bfe6eb290cd094067d2f0R111), [server.py#137](https://github.com/Ananto30/zero/pull/28/files#diff-2f50c53b4b8570b5bb3652e6f0cf315fbd8df68f565bfe6eb290cd094067d2f0R137) and making fixtures in specific folders [tests/single_server/conftest.py#14](https://github.com/Ananto30/zero/pull/28/files#diff-7954c1f549d417728a60c061237b181c1346e959246dc432c6156daa14856091R14), [tests/multiple_servers/conftest.py#10](https://github.com/Ananto30/zero/pull/28/files#diff-315f26a672e579ac3beecd499f0ad8905ba21170119c39e8320fa370916d249cR10))

So I already merged to main, if you rebase, you dont have to spend time on solving that (hopefully, same thing helps in thread)

**Comment by shimondoodkin** [comment]
here it returns value by reference if it works then it works
https://github.com/shimondoodkin/zero/blob/replace-signal-handler-atexit/tests/server_test.py#L72

**Comment by shimondoodkin** [comment]
i was trying to solve the exit problem.
using zmq pooling worked for me in another project and it exited ok nicely and avoided blocking in recv indefinitely.
seems it exiting well when using sigint but not when using sigterm.

seems it is stuck in native module in socket.recv(). 
maybe zmq doesn't handle sigterm, maybe only sigint. 
or
maybe sigterm is switched. maybe it is the reason why it is not working.  could be that it is not calling the previous  original signal sig term signal handler..

**Comment by Ananto30** [comment]
@shimondoodkin very good point! I have introduced `polling` for the sync client. For the async client, there are still some issues. And for the server, I haven't tried polling. Maybe I should.

**Pull request closed without merging**
